name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  setup-jfrog:
    name: Setup JFrog CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JFROG_PLATFORM_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          oidc-provider-name: github-oidc
          oidc-audience: jfrog-github

  test-jfrog:
    name: Test JFrog CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test JFrog CLI
        run: |
          jf rt ping

