on: push
uses: jfrog/setup-jfrog-cli@v3
    env:
        JF_URL: https://elinaf.jfrog.io
	JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    with:
        oidc-provider-name: github-oidc 
        oidc-audience: jfrog-github
    run:
	jf rt ping
